### ISSUE TITLE
Templates not showing up in issues and PRs. 

### ISSUE THREAD

**Issue by qascade** [qascade/yast#57]
@notafk-rajat Normally templates are kept in `.github` but they have stopped coming up in issues after the said change, can you look into this and solve this.

**Comment by notafk-rajat** [comment]
Sure I'll look into this tonight.

**Comment by notafk-rajat** [comment]
Template files should be kept in `.github` folder directly rather than `.github/workflows`. If you assign me this issue I can do it for you, just cut and paste files, or you can do it yourself.

I think just doing this will fix the bug.

Reference - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by qascade** [comment]
Do it in the wsl PR.

**Comment by qascade** [comment]
Closing this, as resolved in #63
